#!/usr/bin/env python3
"""
Download Latin-only woff2 files for Playfair Display, Public Sans and
Source Serif 4, and write fonts/latin.css with local @font-face rules.

  python3 scripts/vendor-fonts.py
"""

from __future__ import annotations

import hashlib
import re
import ssl
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "fonts"
CSS_OUT = OUT_DIR / "latin.css"

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Playfair+Display:ital,wght@0,500;0,600;1,500"
    "&family=Public+Sans:wght@400;500;600"
    "&family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400"
    "&display=swap"
)

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
)

# Keep the Google latin range; drop latin-ext / cyrillic / vietnamese / greek.
LATIN_RANGE_PREFIX = "U+0000-00FF"

FACE_RE = re.compile(r"@font-face\s*\{[^}]+\}", re.S)
URL_RE = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+)\)")
FAMILY_RE = re.compile(r"font-family:\s*'([^']+)'")
STYLE_RE = re.compile(r"font-style:\s*([^;]+);")
WEIGHT_RE = re.compile(r"font-weight:\s*([^;]+);")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    ctx = ssl.create_default_context()
    with urllib.request.urlopen(req, context=ctx, timeout=60) as resp:
        return resp.read()


def slug(family: str, style: str, weight: str, url: str) -> str:
    fam = family.lower().replace(" ", "-")
    st = style.strip().lower()
    wt = weight.strip().replace(" ", "")
    digest = hashlib.sha1(url.encode()).hexdigest()[:8]
    return f"{fam}-{st}-{wt}-{digest}.woff2"


def main() -> int:
    print("Fetching Google Fonts CSS (latin faces only)…")
    css = fetch(GOOGLE_CSS).decode("utf-8")
    faces = FACE_RE.findall(css)
    kept: list[str] = []
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for face in faces:
        if LATIN_RANGE_PREFIX not in face:
            continue
        url_m = URL_RE.search(face)
        fam_m = FAMILY_RE.search(face)
        if not url_m or not fam_m:
            continue
        url = url_m.group(1)
        family = fam_m.group(1)
        style = (STYLE_RE.search(face) or type("m", (), {"group": lambda *_: "normal"})).group(1)
        weight = (WEIGHT_RE.search(face) or type("m", (), {"group": lambda *_: "400"})).group(1)
        name = slug(family, style, weight, url)
        dest = OUT_DIR / name
        if not dest.is_file():
            print(f"  {name}")
            dest.write_bytes(fetch(url))
        else:
            print(f"  {name} (cached)")
        local_url = f"/{dest.relative_to(ROOT).as_posix()}"
        local = re.sub(r"url\([^)]+\)", f"url('{local_url}')", face, count=1)
        kept.append(local)

    if not kept:
        print("ERROR: no Latin @font-face blocks found.", file=sys.stderr)
        return 1

    header = (
        "/* Self-hosted Latin subset. Regenerated by scripts/vendor-fonts.py. */\n"
        "/* Playfair Display, Public Sans, Source Serif 4 — SIL Open Font License 1.1 */\n\n"
    )
    CSS_OUT.write_text(header + "\n\n".join(kept) + "\n", encoding="utf-8")
    print(f"Wrote {CSS_OUT.relative_to(ROOT)} ({len(kept)} faces)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
